
import { Course, Vendor, User, UserRole, Enrollment, CourseMaster } from './types';

// Mock Stats Data
export const ADMIN_STATS_DATA = [
  { name: 'Jan', Users: 400, Vendors: 24, Courses: 240 },
  { name: 'Feb', Users: 300, Vendors: 13, Courses: 221 },
  { name: 'Mar', Users: 200, Vendors: 58, Courses: 229 },
  { name: 'Apr', Users: 278, Vendors: 39, Courses: 200 },
  { name: 'May', Users: 189, Vendors: 48, Courses: 218 },
  { name: 'Jun', Users: 239, Vendors: 38, Courses: 250 },
];

export const VENDOR_COURSE_STATUS_DATA = [
  { name: 'Approved', value: 24, fill: '#10B981' }, // Green
  { name: 'Pending', value: 5, fill: '#F59E0B' },  // Amber
  { name: 'Rejected', value: 3, fill: '#EF4444' },  // Red
];

export const SEAFARER_PROGRESS_DATA = [
  { name: 'Safety', completed: 80, required: 100 },
  { name: 'Navigation', completed: 45, required: 100 },
  { name: 'First Aid', completed: 100, required: 100 },
  { name: 'Engineering', completed: 20, required: 100 },
];

// Helper to generate consistent mock data for fields not in the provided list
const getStatus = (id: number): 'approved' | 'pending' | 'rejected' => {
    if (id % 10 === 0) return 'pending';
    if (id % 15 === 0) return 'rejected';
    return 'approved';
};
const getPrice = (duration: string) => {
    const days = parseInt(duration) || 1;
    return days * 100 + (Math.floor(Math.random() * 50) * 10);
};

export const MOCK_COURSE_MASTERS: CourseMaster[] = [
    { 
        id: '1', 
        code: 'BST-001', 
        title: "Basic STCW Safety Training", 
        category: "Basic", 
        targetAudience: "All Seafarers", 
        courseOverview: "Mandatory safety training for all seafarers covering PST, PSSR, EFA, and FPFF.",
        entryRequirements: "Valid medical certificate",
        additionalNotes: "Bring swimwear for PST",
        status: 'active' 
    },
    { 
        id: '2', 
        code: 'AFF-008', 
        title: "Advanced Fire Fighting", 
        category: "Advanced", 
        targetAudience: "Officers", 
        courseOverview: "Advanced fire prevention and control techniques.",
        entryRequirements: "Basic Fire Fighting Certificate",
        additionalNotes: "Boiler suit required",
        status: 'active' 
    },
    { 
        id: '3', 
        code: 'MFA-014', 
        title: "Medical First Aid", 
        category: "Advanced", 
        targetAudience: "All Seafarers", 
        courseOverview: "First aid onboard ships.",
        entryRequirements: "EFA Certificate",
        additionalNotes: "N/A",
        status: 'active' 
    },
    { 
        id: '4', 
        code: 'GMDSS-023', 
        title: "Global Maritime Distress & Safety System", 
        category: "Simulator", 
        targetAudience: "Radio Officers", 
        courseOverview: "Communication equipment operation.",
        entryRequirements: "COC",
        additionalNotes: "Laptop recommended",
        status: 'active' 
    },
];

// Full Course List
export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: "Basic STCW Safety Training",
    code: "BST-001",
    category: "Basic",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "All Seafarers",
    entryRequirements: "Proof of Indian Citizenship + INDoS Number + Medical Fitness Certificate",
    duration: "12 days",
    validity: "5 years",
    courseOverview: "IMO Model Courses 1.19, 1.20, 1.21 & 1.13; DGS Trg Circular 06/2018",
    additionalNotes: "Bring safety shoes for drills",
    vendorName: "Maritime Inst A",
    price: 1200,
    status: 'approved',
    enrolled: 150,
    rating: 4.8,
    image:"public/assets/STCWBasicSafetyTraining.jpeg"

  },
  {
    id: '2',
    title: "Basic Training Liquified Gas Tanker Cargo Operations",
    code: "BTLGTCO-002",
    category: "Basic",
    courseType: "Tanker",
    mode: "Offline",
    targetAudience: "Officers & personnel handling Liquified Gas Tanker cargo",
    entryRequirements: "Valid Basic Safety STCW (PST/PSSR/EFA/FPFF) OR FPFF Aug OR FPFF + PTFF + Proof of Citizenship + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.04 and STCW Reg V/1-2",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 600,
    status: 'approved',
    enrolled: 85,
    rating: 4.5,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '3',
    title: "Basic Training Oil & Chemical Tanker Cargo Ops",
    code: "BTOCTCO-003",
    category: "Basic",
    courseType: "Tanker",
    mode: "Offline",
    targetAudience: "Officers handling Oil/Chemical tanker cargo",
    entryRequirements: "Valid Basic STCW (PST/PSSR/EFA/FPFF) OR FPFF Aug OR FPFF + PTFF + Proof of Citizenship + INDoS",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.01 & STCW Reg V/1-1",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 700,
    status: 'approved',
    enrolled: 92,
    rating: 4.6,
    image:"public/assets/ProficiencyInSurvivalCraft.jpg"
  },
  {
    id: '4',
    title: "Elementary First Aid",
    code: "EFA-004",
    category: "Basic",
    courseType: "Medical",
    mode: "Offline",
    targetAudience: "All Seafarers with old EFA certificate",
    entryRequirements: "Old EFA Certificate + Indian CDC + INDoS + Proof of Citizenship",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.13",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 350,
    status: 'approved',
    enrolled: 210,
    rating: 4.9,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '5',
    title: "Passenger Ship Familiarization / Crowd Management",
    code: "PSF-005",
    category: "Basic",
    courseType: "Passenger",
    mode: "Hybrid",
    targetAudience: "Personnel employed on passenger ships",
    entryRequirements: "Proof of Citizenship + INDoS",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.28 & DGS Circular 10/2004",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 400,
    status: 'approved',
    enrolled: 65,
    rating: 4.3,
    image:"public/assets/ProficiencyInSurvivalCraft.jpg"
  },
  {
    id: '6',
    title: "Personal Safety & Social Responsibility",
    code: "PSSR-006",
    category: "Basic",
    courseType: "Safety",
    mode: "Online",
    targetAudience: "Seafarers with old PSSR certificate",
    entryRequirements: "Old PSSR + Indian CDC + INDoS + Proof of Citizenship",
    duration: "4 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.21",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 300,
    status: 'approved',
    enrolled: 180,
    rating: 4.7,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '7',
    title: "STSDSD",
    code: "STSDSD-007",
    category: "Basic",
    courseType: "Security",
    mode: "Offline",
    targetAudience: "Seafarers designated for Security Duties",
    entryRequirements: "Citizenship Proof + INDoS Number",
    duration: "2 days",
    validity: "Unlimited",
    courseOverview: "STCW 2010 Sec A-VI/6 & DGS Circular 27/2012",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 250,
    status: 'approved',
    enrolled: 110,
    rating: 4.4,
    image:"public/assets/EngineRoomResourceMgt.jpg"
  },
  {
    id: '8',
    title: "Advanced Fire Fighting",
    code: "AFF-008",
    category: "Advanced",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "Seafarers required to control firefighting operations",
    entryRequirements: "FPFF certificate + Proof of Citizenship + INDoS + Medical Fitness + 1 year sea service (6 months cadets)",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview: "IMO Model Course 2.03 & Annex 2 of IMO Resolution A437(XII)",
    additionalNotes: "Bring safety shoes for drills. AFF Refresher every 5 years",
    vendorName: "Maritime Inst A",
    price: 800,
    status: 'approved',
    enrolled: 75,
    rating: 4.8,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '9',
    title: "Advanced Training Chemical Tanker Cargo Operations",
    code: "ATCTCO-009",
    category: "Advanced",
    courseType: "Tanker",
    mode: "Offline",
    targetAudience: "Officers responsible for handling chemical tanker cargo",
    entryRequirements: "Valid OTF/BTOCTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Proof of Citizenship + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.02 & STCW Reg V/1-1",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 1100,
    status: 'pending',
    enrolled: 0,
    rating: 0,
    image:"public/assets/ChartingFuture.jpg"
  },
  {
    id: '10',
    title: "Advanced Training Liquified Gas Tanker Cargo Operations",
    code: "ATLGTCO-010",
    category: "Advanced",
    courseType: "Tanker",
    mode: "Offline",
    targetAudience: "Masters, Chief Eng., Chief Mates, 2nd Engineers & cargo officers",
    entryRequirements: "Valid GTF/BTLGTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.05 & STCW Reg V/1-2",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 1200,
    status: 'pending',
    enrolled: 0,
    rating: 0,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '11',
    title: "Advanced Training Oil Tanker Cargo Operations",
    code: "ATOTCO-011",
    category: "Advanced",
    courseType: "Tanker",
    mode: "Offline",
    targetAudience: "Officers handling Oil Tanker cargo",
    entryRequirements: "Valid OTF/BTOCTCO + FPFF ('Carry Out Fire-Fighting Ops') + AFF + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.02 & STCW Reg V/1",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 1100,
    status: 'approved',
    enrolled: 40,
    rating: 4.6,
    image:"public/assets/BridgeTeamManagement.jpg"
  },
  {
    id: '12',
    title: "Company Security Officer",
    code: "CSO-012",
    category: "Advanced",
    courseType: "Security",
    mode: "Online",
    targetAudience: "Officers employed or likely to be Company Security Officers",
    entryRequirements: "Company letter / COC / CDC + Citizenship Proof + INDoS (for seafarers)",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.20 & DGS Circular 3/2005",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 450,
    status: 'approved',
    enrolled: 30,
    rating: 4.2,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '13',
    title: "Master Medical Care",
    code: "MC-013",
    category: "Advanced",
    courseType: "Medical",
    mode: "Offline",
    targetAudience: "Masters, Chief Mates & Second Mates responsible for medical care onboard",
    entryRequirements: "MFA + COC Second Mate + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited (tentative)",
    courseOverview: "IMO Model 1.15 & DGS Circular 9/2004",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 900,
    status: 'approved',
    enrolled: 25,
    rating: 4.7,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '14',
    title: "Medical First Aid",
    code: "MFA-014",
    category: "Advanced",
    courseType: "Medical",
    mode: "Hybrid",
    targetAudience: "All Seafarers",
    entryRequirements: "Valid EFA + 6 months onboard service + Citizenship Proof + INDoS",
    duration: "4 days",
    validity: "Unlimited (tentative)",
    courseOverview: "IMO Model 1.14 & STCW Circular 8/2004",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 500,
    status: 'approved',
    enrolled: 120,
    rating: 4.5,
    image:"public/assets/ContainerShip.jpg"
  },
  {
    id: '15',
    title: "MR & UT – Master’s Refresher & Updating",
    code: "MR-0015",
    category: "Advanced",
    courseType: "Refresher",
    mode: "Offline",
    targetAudience: "Certificate of Service (Master FG) holders",
    entryRequirements: "CoS Master FG + INDoS",
    duration: "11 days",
    validity: "5 years",
    courseOverview: "STCW 2010 Training Circular 12/2012",
    additionalNotes: "Requires PSCRB & AFF modules; ECDIS separate",
    vendorName: "Maritime Inst A",
    price: 1500,
    status: 'rejected',
    enrolled: 0,
    rating: 0,
    image:"public/assets/MedicalFirstAid.jpg"
  },
  {
    id: '16',
    title: "Port Facility Security Officer",
    code: "PFSOC-0016",
    category: "Advanced",
    courseType: "Security",
    mode: "Online",
    targetAudience: "Personnel employed as PFSO",
    entryRequirements: "Company letter / COC / CDC + Citizenship Proof + INDoS (for seafarers)",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.21 & DGS Circular 7/2005",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 400,
    status: 'approved',
    enrolled: 55,
    rating: 4.1,
    image:"public/assets/ECDISType-Specific.jpg"
  },
  {
    id: '17',
    title: "Proficiency in Survival Craft & Rescue Boat",
    code: "PSCRB-017",
    category: "Advanced",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "Seafarers operating life-saving appliances or taking charge of rescue crafts",
    entryRequirements: "4 Basic STCW modules + CDC + 1 year sea service (6 months cadets) + Citizenship Proof + INDoS + Medical Fitness",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.23 & DGS Circular 12/2005",
    additionalNotes: "Bring safety shoes, swimming costume & towel; PSCRB Refresher every 5 years",
    vendorName: "Maritime Inst A",
    price: 750,
    status: 'approved',
    enrolled: 90,
    rating: 4.8,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '18',
    title: "Shipboard Safety Officer Course (Value Added)",
    code: "SBSOC-018",
    category: "Advanced",
    courseType: "Safety",
    mode: "Online",
    targetAudience: "Nautical Officers, Engineers, ETOs, Superintendents",
    entryRequirements: "Valid CoC/CoS or sponsorship + 12 months sea service + Passport & CDC",
    duration: "2 days",
    validity: "Unlimited",
    courseOverview: "STCW Code Tables A-II/2, A-III/2 & IMO Model 3.11",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 300,
    status: 'approved',
    enrolled: 45,
    rating: 4.3,
    image:"public/assets/ProficiencyInSurvivalCraft.jpg"
  },
  {
    id: '19',
    title: "Ship Security Officer",
    code: "SSO-019",
    category: "Advanced",
    courseType: "Security",
    mode: "Online",
    targetAudience: "Seafarers designated as SSO",
    entryRequirements: "Company letter / COC / CDC + 12 months sea service + Citizenship Proof + INDoS",
    duration: "3 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 3.19 & DGS Circular 34/2004",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 450,
    status: 'approved',
    enrolled: 89,
    rating: 4.2,
    image:"public/assets/Radar&ARPASimulation.jpg"
  },
  {
    id: '20',
    title: "Vertical Integration Course for Trainers",
    code: "VICT-020",
    category: "Advanced",
    courseType: "Training",
    mode: "Offline",
    targetAudience: "Personnel desiring to be certified as Trainers & Assessors",
    entryRequirements: "INDoS + relevant qualifications per DGS Order 05/2016",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 6.09 & STCW Section V-IV/2",
    additionalNotes: "Formal dress code (suit & tie) for evaluation",
    vendorName: "Maritime Inst A",
    price: 1000,
    status: 'pending',
    enrolled: 0,
    rating: 0,
    image:"public/assets/GMDSSGeneralOperator.jpg"
  },
  {
    id: '21',
    title: "Automatic Radar Plotting Aid",
    code: "ARPA-021",
    category: "Simulator",
    courseType: "Navigation",
    mode: "Offline",
    targetAudience: "NWKOs",
    entryRequirements: "ROSC + 12 months sea service + CDC + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.07; DG Shipping Circular 6/2004",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 800,
    status: 'approved',
    enrolled: 35,
    rating: 4.6,
    image:"public/assets/PST&PSSRCombined.jpg"
  },
  {
    id: '22',
    title: "Electronic Chart Display & Information System",
    code: "ECDIS-022",
    category: "Simulator",
    courseType: "Navigation",
    mode: "Offline",
    targetAudience: "Navigational watch officers using ECDIS",
    entryRequirements: "Deck cadets with 6 months sea service OR deck ratings completing competency + ROSC + ARPA + 3 months bridge watch + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "DG Shipping Circular 29/2012",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 900,
    status: 'approved',
    enrolled: 60,
    rating: 4.7,
    image:"public/assets/ShipSecurityOfficer.jpg"
  },
  {
    id: '23',
    title: "Global Maritime Distress & Safety System",
    code: "GMDSS-023",
    category: "Simulator",
    courseType: "Communication",
    mode: "Offline",
    targetAudience: "Seafarers responsible for radio communication / COC applicants",
    entryRequirements: "10+2 PCM or COC/NWKO + Citizenship Proof + INDoS",
    duration: "12 days",
    validity: "10 years",
    courseOverview: "IMO Model 1.25 & STCW Section V-IV/2",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 1300,
    status: 'approved',
    enrolled: 100,
    rating: 4.8,
    image:"public/assets/TrainningSession.jpg"
  },
  {
    id: '24',
    title: "Radar ARPA Navigation & Simulator Course",
    code: "RANSCO-024",
    category: "Simulator",
    courseType: "Navigation",
    mode: "Offline",
    targetAudience: "2nd Mate COC holders",
    entryRequirements: "ROSC + ARPA + 2nd Mate COC + Citizenship Proof + INDoS",
    duration: "6 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.08 & STCW Circular 7/2004",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 950,
    status: 'approved',
    enrolled: 20,
    rating: 4.5,
    image:"public/assets/ProficiencyInSurvivalCraft.jpg"
  },
  {
    id: '25',
    title: "Radar Observers Simulator Course",
    code: "ROSC-025",
    category: "Simulator",
    courseType: "Navigation",
    mode: "Offline",
    targetAudience: "Seafarers desiring NWKO certification",
    entryRequirements: "12 months sea service + CDC + Citizenship Proof + INDoS",
    duration: "10 days",
    validity: "Unlimited",
    courseOverview: "IMO Model 1.07; DG Shipping Circular 5/2004",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 1100,
    status: 'rejected',
    enrolled: 0,
    rating: 0,
    image:"public/assets/MedicalFirstAid.jpg"
  },
  {
    id: '26',
    title: "Ship Manoeuvring Simulator",
    code: "SMS-026",
    category: "Simulator",
    courseType: "Navigation",
    mode: "Offline",
    targetAudience: "Deck officers at management level",
    entryRequirements: "COC Chief Mate FG / Mate HT + 18 months sea service + Citizenship Proof + INDoS",
    duration: "5 days",
    validity: "Unlimited",
    courseOverview: "DG Shipping Circular 6/2005",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 850,
    status: 'approved',
    enrolled: 15,
    rating: 4.9,
    image:"public/assets/GMDSSGeneralOperator.jpg"
  },
  {
    id: '27',
    title: "Fire Prevention & Fire Fighting Refresher",
    code: "FPFFR-027",
    category: "Refresher",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "Seafarers with FPFF valid 5 years earlier",
    entryRequirements: "Valid FPFF / FPFF R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 6/2011 & STCW Table A-VI/1-2",
    additionalNotes: "Bring safety shoes",
    vendorName: "Ocean Academy",
    price: 150,
    status: 'approved',
    enrolled: 200,
    rating: 4.4,
    image:"public/assets/ECDISType-Specific.jpg"
  },
  {
    id: '28',
    title: "Medical Care Refresher & Updating Training",
    code: "MCRUT-028",
    category: "Refresher",
    courseType: "Medical",
    mode: "Hybrid",
    targetAudience: "Officers holding MC/MC RUT valid 5 years earlier",
    entryRequirements: "Valid MC / MC RUT + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 17/2013 & MLC 2006",
    additionalNotes: "—",
    vendorName: "Blue Sea Corp",
    price: 200,
    status: 'approved',
    enrolled: 50,
    rating: 4.3,
    image:"public/assets/ContainerShip.jpg"
  },
  {
    id: '29',
    title: "Medical First Aid Refresher",
    code: "MFARUT-029",
    category: "Refresher",
    courseType: "Medical",
    mode: "Hybrid",
    targetAudience: "MFA/MFA RUT holders 5 years old",
    entryRequirements: "Valid MFA / MFA RUT + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 17/2013 & MLC 2006",
    additionalNotes: "—",
    vendorName: "Maritime Inst A",
    price: 180,
    status: 'approved',
    enrolled: 80,
    rating: 4.5,
    image:"public/assets/ChemicalTankerFamiliarization.jpg"
  },
  {
    id: '30',
    title: "Personal Survival Techniques Refresher",
    code: "PSTR-030",
    category: "Refresher",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "PST / PST R holders 5 years old",
    entryRequirements: "Valid PST / PST R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping Circular 6/2011 & STCW Table A-VI/1-1",
    additionalNotes: "Bring swimwear & towel",
    vendorName: "Ocean Academy",
    price: 150,
    status: 'approved',
    enrolled: 220,
    rating: 4.6,
    image:"public/assets/ChartingFuture.jpg"
  },
  {
    id: '31',
    title: "Advance Fire Fighting Refresher",
    code: "AFFR-031",
    category: "Refresher",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "Officers holding AFF / AFF R older than 5 years",
    entryRequirements: "Valid AFF / AFF R / AFFFPFF R + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DG Shipping ENGG Circular 2/2015",
    additionalNotes: "Bring safety shoes",
    vendorName: "Maritime Inst A",
    price: 250,
    status: 'approved',
    enrolled: 100,
    rating: 4.7,
    image:"public/assets/BridgeTeamManagement.jpg"
  },
  {
    id: '32',
    title: "Proficiency in Survival Craft Refresher",
    code: "PSCRBR-032",
    category: "Refresher",
    courseType: "Safety",
    mode: "Offline",
    targetAudience: "PSCRB holders",
    entryRequirements: "Valid PSCRB + Citizenship Proof + INDoS",
    duration: "1 day",
    validity: "5 years",
    courseOverview: "DGS training requirement",
    additionalNotes: "—",
    vendorName: "Ocean Academy",
    price: 250,
    status: 'pending',
    enrolled: 0,
    rating: 0,
    image:"public/assets/AdvancedFireFighting.jpg"
  },
];

export const MOCK_VENDORS: Vendor[] = [
  { 
    id: '1', 
    companyName: 'Maritime Inst A', 
    status: 'active', 
    totalCourses: 12,
    email: 'contact@maritimeinste.com',
    phone: '+91 98765 43210',
    address: '42 Port Road, Mumbai, India',
    website: 'www.maritimeinste.com',
    accreditation: 'DGS-1002',
    foundedYear: '1995',
    contactPerson: 'Capt. R. Kumar',
    description: 'Maritime Inst A is a premier institution with over 25 years of excellence in maritime training.',
    licenseNumber: 'LIC-MIA-001',
    issuingAuthority: 'DG Shipping India',
    customerCareEmail: 'support@maritimeinste.com',
    customerCarePhone: '+91 22 2345 6789',
    coursesOffered: ['Basic STCW Safety', 'Advanced Fire Fighting', 'ECDIS', 'GMDSS'],
    documents: [{ name: 'Accreditation Cert.pdf', type: 'application/pdf', date: '2023-01-15' }]
  },
  { 
    id: '2', 
    companyName: 'Ocean Academy', 
    status: 'active', 
    totalCourses: 8,
    email: 'admissions@oceanacademy.com',
    phone: '+91 91234 56789',
    address: '15 Sea View, Chennai, India',
    website: 'www.oceanacademy.com',
    accreditation: 'DGS-2045',
    foundedYear: '2005',
    contactPerson: 'Mr. S. Sharma',
    description: 'Ocean Academy focuses on modern simulation based training for advanced seafarers.',
    licenseNumber: 'LIC-OA-2045',
    issuingAuthority: 'DG Shipping India',
    customerCareEmail: 'care@oceanacademy.com',
    customerCarePhone: '+91 44 8765 4321',
    coursesOffered: ['GMDSS', 'Medical First Aid', 'PSSR'],
    documents: [{ name: 'ISO 9001 Cert.pdf', type: 'application/pdf', date: '2023-03-22' }]
  },
  { 
    id: '3', 
    companyName: 'Blue Sea Corp', 
    status: 'pending', 
    totalCourses: 1,
    email: 'info@bluesea.com',
    phone: '+91 99887 76655',
    address: '88 Harbour Line, Kolkata, India',
    website: 'www.blueseacorp.com',
    accreditation: 'Pending',
    foundedYear: '2023',
    contactPerson: 'Mrs. A. Das',
    description: 'A new venture aiming to provide affordable quality training for fresh cadets.',
    licenseNumber: 'LIC-PEND-003',
    issuingAuthority: 'DG Shipping India',
    customerCareEmail: 'help@blueseacorp.com',
    customerCarePhone: '+91 33 2222 3333',
    coursesOffered: ['Basic STCW Safety'],
    documents: [{ name: 'Application Form.pdf', type: 'application/pdf', date: '2023-11-01' }]
  },
  { 
      id: '4', 
      companyName: 'Global Seafarers Hub', 
      status: 'rejected', 
      totalCourses: 0,
      email: 'contact@gshub.com',
      phone: '+91 90000 11111',
      address: 'Industrial Area, Vizag, India',
      website: 'www.gshub.com',
      accreditation: 'Rejected-404',
      foundedYear: '2023',
      contactPerson: 'Mr. J. Doe',
      description: 'Rejected due to insufficient facility proof.',
      licenseNumber: 'REJECTED-001',
      issuingAuthority: 'DG Shipping India',
      customerCareEmail: 'info@gshub.com',
      customerCarePhone: '+91 90000 22222',
      coursesOffered: [],
      documents: []
    },
];

export const MOCK_ENROLLMENTS: Enrollment[] = [
  { id: '1', studentName: 'Jack Sparrow', courseTitle: 'Basic STCW Safety Training', enrollmentDate: '2023-10-15', status: 'active', email: 'jack@pearl.com', phone: '+44 7700 900077', progress: 45 },
  { id: '2', studentName: 'Will Turner', courseTitle: 'Advanced Fire Fighting', enrollmentDate: '2023-11-01', status: 'completed', email: 'will@dutchman.com', phone: '+44 7700 900011', progress: 100 },
  { id: '3', studentName: 'Elizabeth Swann', courseTitle: 'Medical First Aid', enrollmentDate: '2023-11-05', status: 'active', email: 'liz@royal.com', phone: '+44 7700 900022', progress: 20 },
  { id: '4', studentName: 'Hector Barbossa', courseTitle: 'GMDSS', enrollmentDate: '2023-10-20', status: 'cancelled', email: 'hector@blackpearl.com', phone: '+44 7700 900033', progress: 0 },
  { id: '5', studentName: 'Joshamee Gibbs', courseTitle: 'Basic STCW Safety Training', enrollmentDate: '2023-11-10', status: 'active', email: 'gibbs@pearl.com', phone: '+44 7700 900044', progress: 60 },
  { id: '6', studentName: 'James Norrington', courseTitle: 'ECDIS Type Specific', enrollmentDate: '2023-09-15', status: 'completed', email: 'james@navy.com', phone: '+44 7700 900055', progress: 100 },
  { id: '7', studentName: 'Davy Jones', courseTitle: 'Ship Security Officer', enrollmentDate: '2023-10-31', status: 'active', email: 'davy@locker.com', phone: '+44 7700 900066', progress: 10 },
  { id: '8', studentName: 'Bootstrap Bill', courseTitle: 'Basic STCW Safety Training', enrollmentDate: '2023-11-12', status: 'active', email: 'bill@dutchman.com', phone: '+44 7700 900088', progress: 30 },
  { id: '9', studentName: 'Cutler Beckett', courseTitle: 'Company Security Officer', enrollmentDate: '2023-09-01', status: 'completed', email: 'lord@eic.com', phone: '+44 7700 900099', progress: 100 },
  { id: '10', studentName: 'Tia Dalma', courseTitle: 'Medical First Aid', enrollmentDate: '2023-10-05', status: 'active', email: 'calypso@sea.com', phone: '+44 7700 900000', progress: 55 },
  { id: '11', studentName: 'Sao Feng', courseTitle: 'GMDSS', enrollmentDate: '2023-11-02', status: 'active', email: 'feng@singapore.com', phone: '+65 6789 0000', progress: 15 },
  { id: '12', studentName: 'Pintel', courseTitle: 'Basic STCW Safety Training', enrollmentDate: '2023-11-15', status: 'active', email: 'pintel@pearl.com', phone: '+44 7700 900111', progress: 5 },
  { id: '13', studentName: 'Ragetti', courseTitle: 'Basic STCW Safety Training', enrollmentDate: '2023-11-15', status: 'active', email: 'ragetti@pearl.com', phone: '+44 7700 900222', progress: 5 },
];

// Mock Users Data (Detailed JSON)
export const MOCK_USERS: Record<string, User> = {
  admin: {
    id: 'admin-1',
    name: 'Administrator',
    email: 'admin@sealearn.com',
    role: UserRole.ADMIN,
    status: 'active',
    password: 'admin123',
    avatarUrl: 'https://picsum.photos/seed/admin/200/200',
    phone: '+1 555 000 0000',
    address: 'HQ, Silicon Valley',
    details: {
      department: 'Operations',
      accessLevel: 'Super Admin',
      lastLogin: '2023-10-25 09:00:00'
    }
  },
  vendor: {
    id: 'vendor-1',
    name: 'Global Maritime Institute',
    email: 'contact@globalmaritime.com',
    role: UserRole.VENDOR,
    status: 'active',
    password: 'vendor123',
    avatarUrl: 'https://picsum.photos/seed/vendor/200/200',
    phone: '+65 6789 1234',
    address: '12 Marina Boulevard, Singapore',
    details: {
      website: 'www.globalmaritime.com',
      accreditation: 'ISO 9001:2015',
      founded: '1998',
      licenseNumber: 'EDU-2023-8899',
      specialization: ['Safety', 'Navigation', 'Engineering']
    }
  },
  seafarer: {
    id: 'seafarer-1',
    name: 'Capt. Jack Sparrow',
    email: 'jack@pearl.com',
    role: UserRole.SEAFARER,
    status: 'active',
    password: 'user123',
    avatarUrl: 'https://picsum.photos/seed/seafarer/200/200',
    phone: '+44 7700 900077',
    address: 'Port Royal, Caribbean',
    details: {
      rank: 'Master',
      nationality: 'British',
      dob: '1980-05-15',
      cdcNumber: 'UK-987654321',
      experience: '15 Years',
      nextAvailability: '2023-12-01',
      vesselTypes: ['Container', 'Tanker', 'Black Pearl']
    }
  }
};

// Flattened User List for Admin Table
export const MOCK_USER_LIST: User[] = [
    MOCK_USERS.admin,
    MOCK_USERS.vendor,
    MOCK_USERS.seafarer,
    // Add extra dummy users for table demonstration
    {
        id: 'seafarer-2',
        name: 'Will Turner',
        email: 'will@dutchman.com',
        role: UserRole.SEAFARER,
        status: 'active',
        phone: '+44 7700 900011',
        address: 'Flying Dutchman',
        details: { rank: 'Chief Officer', nationality: 'British' }
    },
    {
        id: 'vendor-2',
        name: 'Ocean Academy',
        email: 'admissions@oceanacademy.com',
        role: UserRole.VENDOR,
        status: 'active',
        phone: '+91 91234 56789',
        address: 'Chennai, India',
        details: { website: 'oceanacademy.com' }
    },
    {
        id: 'seafarer-3',
        name: 'Hector Barbossa',
        email: 'hector@blackpearl.com',
        role: UserRole.SEAFARER,
        status: 'disabled',
        phone: '+44 7700 900033',
        address: 'Unknown',
        details: { rank: 'Master', nationality: 'Spanish' }
    },
    {
        id: 'seafarer-4',
        name: 'Elizabeth Swann',
        email: 'liz@royal.com',
        role: UserRole.SEAFARER,
        status: 'active',
        phone: '+44 7700 900022',
        address: 'Port Royal',
        details: { rank: 'Pirate King', nationality: 'British' }
    },
    {
        id: 'vendor-3',
        name: 'Blue Sea Corp',
        email: 'info@bluesea.com',
        role: UserRole.VENDOR,
        status: 'disabled',
        phone: '+91 99887 76655',
        address: 'Kolkata, India',
        details: { website: 'blueseacorp.com' }
    }
];
